apiVersion: v1
kind: Namespace
metadata:
  name: your-namespace
---
apiVersion: networking.k8s.io/v1
kind: Service
metadata:
  name: mongodb-service
  namespace: your-namespace
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: networking.k8s.io/v1
kind: Service
metadata:
  name: postgresql-service
  namespace: your-namespace
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: combined-deployment
  namespace: your-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: combined-database
  template:
    metadata:
      labels:
        app: combined-database
    spec:
      containers:
      - name: mongodb
        image: your-mongo-image:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: your_mongo_username
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: your_mongo_password
      - name: postgresql
        image: your-postgres-image:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: your_postgres_username
        - name: POSTGRES_PASSWORD
          value: your_postgres_password
        - name: POSTGRES_DB
          value: your_postgres_database
